### PR TITLE
Added op support for enemy lists

### PR DESCRIPTION
**Pull request by smartin015**
This allows for three formats of enemy within a combat node:

```
_combat_

- Skeleton Swordsman
- {{anEnemyExpression}}
- {{condition}} BadGuy
```

The first is a standard enemy, with no additional parsing.

The second evaluates the expression and uses the result value as the enemy.

The third conditionally shows the enemy based on the expression's evaluation result.

### CODE REVIEW

**Comment by toddmedema** [comment]
Looks good! Only thought - do we want to keep support for enemies in the JSON list, even if it's not the publicly documented way? Seems like it'd be straightforward to support both (they're both lists at the end of the day)

**Comment by smartin015** [comment]
It's already supported :) this doesn't remove JSON list assignment.

**Comment by toddmedema** [comment]
Ah gotcha. Looks like the JSON test case was replaced by the list test case? (which is probs why I got confused) - might be worth keeping test cases for both

**Comment by smartin015** [comment]
Now we have a separate test for setting enemies via JSON.

**Comment by toddmedema** [comment]
Lgtm

**Pull request merged**
