### PR TITLE
Combat: hyphenated enemy lists

### PR DESCRIPTION
**Pull request by smartin015**
Also removed all instances of modifying blocks after generation, to prevent things like getResultAt from failing in weird ways.

### CODE REVIEW

**Comment by smartin015** [comment]
#43

**Comment by toddmedema** [comment]
Matching test updates?

**Comment by smartin015** [comment]
Well, I updated the tests.... and then refactored the whole damn thing.

Upside, there's even more tests now. And more unwritten stubs.

**Comment by toddmedema** [comment]
LGTM

**Pull request merged**
